# Generated by Django 3.1.5 on 2021-01-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='UserPics')),
                ('fname', models.CharField(max_length=35)),
                ('lname', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=40)),
                ('linkedin', models.URLField()),
                ('insta', models.URLField()),
                ('twitter', models.URLField(max_length=220)),
                ('fb', models.URLField(max_length=220)),
                ('hobby', models.CharField(max_length=100)),
                ('describe', models.TextField()),
            ],
        ),
    ]
