# Generated by Django 3.1.5 on 2021-01-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackclass',
            name='feedback',
            field=models.CharField(blank=True, choices=[('Comments', 'Comments'), ('Suggestions', 'Suggestions'), ('Questions', 'Questions')], max_length=20, null=True),
        ),
    ]
