# Generated by Django 3.1.5 on 2021-01-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20210128_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackclass',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackclass',
            name='lname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
