# Generated by Django 3.1.5 on 2021-01-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20210128_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackclass',
            name='email',
            field=models.EmailField(default=False, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedbackclass',
            name='feedback',
            field=models.CharField(choices=[('Comments', 'Comments'), ('Suggestions', 'Suggestions'), ('Questions', 'Questions')], default=False, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedbackclass',
            name='fname',
            field=models.CharField(default=False, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedbackclass',
            name='lname',
            field=models.CharField(default=False, max_length=20),
            preserve_default=False,
        ),
    ]
