# Generated by Django 3.1.5 on 2021-01-28 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20210128_0247'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feedbackClass',
            new_name='feedbackModel',
        ),
    ]
