# Generated by Django 3.1.5 on 2021-01-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20210128_0456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackmodel',
            old_name='feedback',
            new_name='FeedbackType',
        ),
        migrations.RenameField(
            model_name='feedbackmodel',
            old_name='fname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='feedbackmodel',
            old_name='lname',
            new_name='lastname',
        ),
        migrations.AddField(
            model_name='feedbackmodel',
            name='subject',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
