# Generated by Django 3.1.5 on 2021-02-01 09:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_uploads'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('editor', ckeditor.fields.RichTextField()),
                ('tags', models.CharField(max_length=25)),
            ],
        ),
    ]
