# Generated by Django 3.1.5 on 2021-02-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='title',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='topic',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
