# Generated by Django 3.1.5 on 2021-02-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_auto_20210201_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='tags',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='topic',
            field=models.CharField(default=True, max_length=25),
            preserve_default=False,
        ),
    ]
