# Generated by Django 3.1.5 on 2021-02-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_auto_20210201_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default=False, max_length=30),
            preserve_default=False,
        ),
    ]
