# Generated by Django 3.1.5 on 2021-02-02 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_blogpost_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
    ]
