# Generated by Django 3.1.5 on 2021-02-02 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0022_auto_20210202_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
    ]
