# Generated by Django 3.1.5 on 2021-02-04 06:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0024_blogpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
