# Generated by Django 3.1.5 on 2021-02-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0026_blogpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='topic',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Mathematics', 'Mathematics'), ('Social Media', 'Social Media')], max_length=25),
        ),
    ]
