# Generated by Django 3.1.5 on 2021-02-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0029_auto_20210206_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='topic',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Mathematics', 'Mathematics'), ('Social Media', 'Social Media')], max_length=25, null=True),
        ),
    ]
