# Generated by Django 3.1.5 on 2021-02-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0031_likesystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='likeField',
            field=models.BooleanField(default=False),
        ),
    ]
