# Generated by Django 3.1.5 on 2021-02-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0032_feedbackmodel_likefield'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeSystem',
        ),
    ]
