# Generated by Django 3.1.5 on 2021-02-07 05:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0033_delete_likesystem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='likeField',
        ),
        migrations.AddField(
            model_name='feedbackmodel',
            name='likeField',
            field=models.ManyToManyField(related_name='blog_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
