# Generated by Django 3.1.5 on 2021-01-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(default=True, max_length=25),
            preserve_default=False,
        ),
    ]
