# Generated by Django 3.1.5 on 2021-01-29 09:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_blogpost_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='BlogData',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='title',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='editor',
            field=ckeditor.fields.RichTextField(default=True),
            preserve_default=False,
        ),
    ]
