# Generated by Django 3.1.5 on 2021-01-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210129_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.ImageField(upload_to='UserPics')),
                ('firstname', models.CharField(max_length=35)),
                ('lastname', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=40)),
                ('linkedin', models.URLField()),
                ('instagram', models.URLField()),
                ('twitter', models.URLField(max_length=220)),
                ('facebook', models.URLField(max_length=220)),
                ('hobby', models.CharField(max_length=100)),
                ('subject', models.TextField()),
            ],
        ),
    ]
