# Generated by Django 3.1.5 on 2021-01-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='filename',
            field=models.FileField(upload_to='UserPics'),
        ),
    ]
