# Generated by Django 3.1.5 on 2021-01-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210130_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='filename',
            field=models.ImageField(upload_to='UserPics'),
        ),
    ]
