# Generated by Django 3.1.5 on 2021-02-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210130_1030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='filename',
            field=models.FileField(upload_to='UserPics'),
        ),
    ]
