# Generated by Django 3.1.5 on 2021-02-02 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_userprofile_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='author',
        ),
    ]
