# Generated by Django 3.1.5 on 2021-02-06 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_likesystem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeSystem',
        ),
    ]
